name: Android CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare script
        run: chmod +x .github/scripts/gradlew_recursive.sh
      - name: Build project
        run: .github/scripts/gradlew_recursive.sh assembleDebug
      - name: Test project
        run: .github/scripts/gradlew_recursive.sh testDebug
      - name: Zip artifacts
        run: zip -r assemble.zip . -i '**/build/*.apk' '**/build/*.aab' '**/build/*.aar' '**/build/*.so'
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: assemble
          path: assemble.zip